name: Deploy to Github Pages

on:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      GATSBY_GITHUB_API_TOKEN: ${{ secrets.GATSBY_GITHUB_API_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
