name: Deploy to Github Pages

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env: ${{ secrets.GATSBY_GITHUB_API_TOKEN }}
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
